---
title: "Steps For Creating/Using Report Templates"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Steps For Creating/Using Report Templates}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Introduction 

The AE summaries application is aimed to provide an interface to generate safety analysis results in interactive and dynamic for Adverse Event. 

## steps to create templates 
1. Data processing 
2. Risk radio, risk diff, n(%) calculation
3. graphincal Representation 
4. Calling all the parameter of the utility in Yaml 

## Forest Plot template
1. list of Parameters and valid values

- Population_Filter: Analysid population filters. Valid values: Overall, Safety,  Intent to Treat,  Modified Intent to Treat,  Per Protocol,  Randomised
- data_filter: Adverse Event data filter. Valid Values:  "Treatment Emergent",   "Serious",  "Drug-related",  "Mild",  "Moderate",  "Severe",                             "Recovered/Resolved",  "Recovering/Resolving", "Not Recovered/Not Resolved",  "Fatal"
- trtvar: Treatment variable present in the input dataset (Example : "TRTA")
- obs_period: duration of event to be analyzed. Valid Values: "Overall Duration"
- obs_residual: the numeric value of the additional duration days
- review_by: The event variable. Valid values: "PT", "SOC"
- summary_by: Review the data by count of event or count of absect by event. valid values: "Patients", "Event"
- ctrlgrp: the treatment value present in the treatment variable given in TRTVAR (Example:"Placebo")
- trtgrp: the treatment value present in the treatment variable given in TRTVAR (Example: "Xanomeline High Dose")
- alpha: Numeric value for confidence interval calculation between 0 to 1 (Example: 0.05)
- cutoff: the cutoff percent value for the patient or event count between 0-10 (Example: 5)
- sort_opt: the order in which data should be ordered "Ascending", "Descending", "Alphabetical" 
- sort_var: the ordering variable "Ascending", "Descending" sorting. valid values: "Count"  "Percent", "RiskValue"
- statistics: the inferential statistics to be calculated. valid values: "Risk Ratio", "Risk Difference"
- xlims: the Xaxis limits for risk values. (Example: c(0, 3))
- xref: X axis reference line. (Example: 0)
- pvalcut: pvalue cutoff to determine the significant event. (Example:0.05)
  
2. input data, Currently point to the CDISC data present in the data folder. Add the required input file to data folder. 

3. Output generated is a html plotly output. 

