---
title: "Event Analysis Plot"
output:
  html_document:
    df_print: paged
params:
  Population_Filter: "Overall"
  data_filter: ""
  trtvar: "TRTA"
  obs_period: "Overall Duration"
  obs_residual: 28
  pop: "SAFFL=='Y'"
  query_var: "FMQ_NAM"
  query_val: "Erythema"
  query_scope: "Narrow"
  pt_val: "Erythema"
  ref_line: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(haven)
library(tidyverse)
library(cowplot)
library(epitools)
library(plotly)
library(ggstance)
library(scales)
library(admiral)
library(tidyCDISC)
source("../R/data_processing.R")
source("../R/event_analysis.R")
source("../R/title_ftnote.R")
source("../R/adsl_merge.R")
```


```{r processing, include=FALSE }


adsl_merge <- adsl_merge(data=read_sas("../data/adsl.sas7bdat"), 
                         pop=params$pop, 
                         dataset_add=read_sas("../data/adae.sas7bdat")
                         ) 


data_in <- data_processing(
  datain = adsl_merge,
  Population_Filter = params$Population_Filter,
  data_filter = params$data_filter,
  trtvar = params$trtvar,
  obs_period = params$obs_period,
  obs_residual = params$obs_residual,
  fmq_query_list = read.csv("../data/FMQ_Consolidated_List.csv")
)


goutput <- event_analysis(
  data_in,
  query_var=params$query_var,
  query_val=params$query_val,
  query_scope=params$query_scope,
  pt_val=params$pt_val,
  ref_line=params$ref_line
)



ft_out <- title_ftnote(
  summary_by = "Events",
  filters = NULL,
  statistics = NULL,
  report = "event analysis"
)
```



```{r , include=TRUE, echo=FALSE, fig.height=5, fig.width=10, results="asis"}
cat(gsub(pattern = "\n", replacement = "  \n", x = ft_out[1]),"\n")
goutput$ptly
cat(gsub(pattern = "\n", replacement = "  \n", x = ft_out[2]),"\n")
```

