---
title: "Adverse Event Forest Plot"
output:
  html_document:
    df_print: paged
params:
  Population_Filter: "Safety"
  data_filter: ""
  trtvar: "TRTA"
  obs_period: "Overall Duration"
  obs_residual: 28
  review_by: "PT"
  summary_by: "Patients"
  ctrlgrp: "Placebo"
  trtgrp: "Xanomeline High Dose"
  alpha: 0.05
  cutoff: 5
  sort_opt: "Ascending"
  sort_var: "Count"
  statistics: "Risk Ratio"
  xlims: c(0, 3)
  xref: 0
  pvalcut: 0.05
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(haven)
library(tidyverse)
library(cowplot)
library(epitools)
library(plotly)
library(ggstance)
library(scales)
source("../R/data_processing.R")
source("../R/GetStatistics.R")
source("../R/RiskDiff.R")
source("../R/forest_plot.R")
source("../R/title_ftnote.R")
```


```{r processing, include=FALSE}

data_in <- data_processing(
  datain = read_sas("../data/adae.sas7bdat"),
  Population_Filter = params$Population_Filter,
  data_filter = params$data_filter,
  trtvar = params$trtvar,
  obs_period = params$obs_period,
  obs_residual = params$obs_residual,
  fmq_query_list = read.csv("../data/FMQ_Consolidated_List.csv")
)

statistics <<- GetStatistics_all(
  data = data_in,
  review_by = params$review_by,
  summary_by = params$summary_by,
  ctrlgrp = params$ctrlgrp,
  trtgrp = params$trtgrp,
  statistics = params$statistics,
  alpha = params$alpha,
  cutoff = params$cutoff,
  sort_opt = params$sort_opt,
  sort_var = params$sort_var
)

goutput <- Forest_Plot(
  dat = statistics,
  review_by = params$review_by,
  summary_by = params$summary_by,
  statistics = params$statistics,
  xlims = c(0, 3),
  xref =params$xref,
  pvalcut = params$pvalcut
)

ft_out <- title_ftnote(
  summary_by = params$summary_by,
  filters = params$data_filter,
  statistics = params$statistics,
  report = "Forest"
)
```



```{r , echo = FALSE, warning = FALSE, message = FALSE, results="asis"}

cat(gsub(pattern = "\n", replacement = "  \n", x = ft_out[1]),"\n")
goutput$ptly
cat(gsub(pattern = "\n", replacement = "  \n", x = ft_out[2]),"\n")
```

