#' Function to generate Volcano Plot of Adverse Events data from Risk values of treatment pairs
#'
#' @param datain (`list of data.frame`)\cr AE dataset after pre-processing for filters
#' using `ae_pre_processor()`.
#' @param AE_Filter (`character`)\cr Adverse Event filter selected, used for footnote.
#' @param statistics_data (`data.frame`)\cr Input dataset containing statistics for treatment
#' pairs from AE data, generated by `risk_stat()`.
#' @param statistics (`character`)\cr Statistic which was calculated in statistics_data.
#' Expected Values: `Risk Difference`/`Risk Ratio`.
#' @param treatment1 (`character`)\cr Control treatment.
#' @param treatment2 (`character`)\cr Exposure/comparison treatment.
#' @param X_ref (`numeric`)\cr X intercept value to draw vertical reference lines in plot.
#' @param summary_by (`character`)\cr Calculated summaries by; used for footnote.
#' Expected Values: `Patients`/`Events`.
#' @param pvalue_label (`character`)\cr P-value transformation. Expected Values: `-log10`, `None`
#' @param treatment1_label (`character`)\cr Label for treatment1 in plot title
#' @param treatment2_label (`character`)\cr Label for treatment2 in plot title
#' @param pvalcut (`numeric`)\cr p-value cut-off, filter values with adjusted `p` less than
#' `pvalcut`.
#'
#' @return a list containing 5 elements
#' \itemize{
#' \item ptly - Interactive plotly output to be displayed
#' \item plot - Static plot output
#' \item rpt_data - Data used to create report for download/QC
#' \item title - String to use as report title
#' \item footnote - String to use as report footnote
#' }
#' @export
#'
#' @examples
#'
#' library(cvars)
#'
#' vout <- volcano_plot(
#'   datain = ae_pre,
#'   AE_Filter = "Safety",
#'   statistics_data = ae_risk,
#'   statistics = "Risk Difference",
#'   treatment1 = "Placebo",
#'   treatment2 = "Xanomeline Low Dose",
#'   X_ref = 1,
#'   summary_by = "Patients",
#'   pvalue_label = "None",
#'   treatment1_label = "Control",
#'   treatment2_label = "Exposure",
#'   pvalcut = 0.05
#' )
#'
#' vout$ptly
#'
volcano_plot <- function(datain,
                         AE_Filter,
                         statistics_data,
                         statistics,
                         treatment1,
                         treatment2,
                         X_ref,
                         summary_by,
                         pvalue_label,
                         treatment1_label,
                         treatment2_label,
                         pvalcut) {
  ### Construction of volcano plot
  # Check if getstats data is empty:
  if (nrow(statistics_data) == 0) {
    p <- ggplot() +
      annotate(
        "text",
        x = 4,
        y = 25,
        size = 8,
        label = "No data selected for plot."
      ) +
      theme_bw() +
      theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank()
      )
    return(list(plot = p, rpt_data = datain))
  }

  statistics_data <- statistics_data %>% filter(RISK != Inf)

  N1_Total <-
    statistics_data[statistics_data$TRTVAR == treatment1, ]$TOTAL_N
  N2_Total <-
    statistics_data[statistics_data$TRTVAR == treatment2, ]$TOTAL_N
  # Key for listings
  key <- row.names(statistics_data)

  # Error when there are no adjusted p-values <= 0.05 so remove FDR adjusted P when no
  # adjusted p <= 0.05
  check_sig <- statistics_data %>%
    group_by() %>%
    filter(ADJPVALUE <= pvalcut)
  p <-
    ggplot(
      statistics_data,
      aes(
        RISK,
        PVALUE,
        text = HOVER_TEXT,
        key = key,
        fill = BYVAR1
      )
    ) + # color code by SOC
    geom_point(aes(size = CTRL_N), pch = 21, alpha = 0.5)

  if (nrow(check_sig) != 0) {
    pvalue_adj <-
      (
        statistics_data %>%
          group_by() %>%
          filter(ADJPVALUE <= pvalcut) %>%
          arrange(desc(ADJPVALUE)) %>%
          slice(1)
      )$PVALUE
    p <- p +
      geom_hline(
        yintercept = pvalue_adj,
        color = "grey30",
        linetype = "dotted"
      )
  }
  p <- p +
    geom_hline(
      yintercept = pvalcut,
      color = "grey30",
      linetype = "dashed"
    ) +
    geom_vline(
      xintercept = ifelse(grepl("Ratio", statistics), 1, 0),
      color = "grey30",
      linetype = "dashed"
    ) +
    geom_vline(
      xintercept = ifelse(grepl("Ratio", statistics), 1, 0) + c(-X_ref, X_ref),
      color = "grey30",
      linetype = "dashed"
    ) +
    theme_classic() +
    cowplot::background_grid(
      major = "xy",
      minor = "none",
      color.major = "grey92"
    ) +
    # guides(fill=guide_legend(title = "System Organ Class",title.position="top"),size="none")+
    theme(
      legend.position = "bottom",
      legend.text = element_text(size = 6)
    ) +
    scale_size_continuous(name = "", range = c(1, 8)) +
    scale_fill_discrete(name = " ")


  ### P value transformation
  if (pvalue_label == "-log10") {
    p <- p + scale_y_continuous(
      "-log10(p-value)",
      trans = reverselog_trans(10),
      breaks = as.numeric(paste0("1e-", 0:20)),
      labels = as.character(0:20),
      expand = expansion(mult = c(0.05, 0.05))
    )
  } else if (pvalue_label == "None") {
    p <- p + scale_y_continuous(
      "P-value",
      trans = reverselog_trans(10),
      breaks = c(0.05, 0, rep(1, 10) / 10^(9:0)),
      labels = as.character(c(0.05, 0, rep(1, 10) / 10^(9:0))),
      expand = expansion(mult = c(0.05, 0.05))
    )
  }

  text1 <- paste0(
    "<- Favors ", treatment1_label,
    " (N=", N1_Total, ")"
  )
  text2 <- paste0(
    "Favors ", treatment2_label,
    " (N=", N2_Total, ") ->"
  )

  lab1 <-
    paste(statistics, treatment1_label, "vs.", treatment2_label)
  lab2 <- paste(text1, text2)

  label_fin <- unique(paste0(lab2, "\n", lab1))

  output <-
    plotly::ggplotly(
      p,
      tooltip = c("text"),
      source = "plot_output",
      height = 800,
      width = 800
    ) %>%
    plotly::layout(
      legend = list(
        font = list(size = 8.5),
        orientation = "h",
        x = 0.4,
        y = -0.2
      ),
      title = list(text = ""),
      xaxis = list(title = unique(paste0(lab2, "<br>", lab1))),
      yaxis = list(title = "")
    )

  p <- p +
    scale_x_continuous(label_fin, expand = expansion(mult = c(0.05, 0.05))) +
    theme(plot.title = element_text(hjust = 0.5))


  # Title Footnote Processing
  if (is.null(AE_Filter)) {
    AE_Filter <- ""
  }
  AE_cond <- ifelse(length(AE_Filter) <= 1,
    AE_Filter,
    paste0(
      paste0(AE_Filter[-length(AE_Filter)],
        collapse = ", "
      ),
      " and ",
      AE_Filter[length(AE_Filter)]
    )
  )
  title <-
    paste0("Volcano plot for ", statistics, " of ", AE_cond, " Adverse Events")
  footnote <- paste0(
    "* N is the total number of ",
    ifelse(tolower(summary_by) == "patients", "participants", "events"),
    ". \n",
    "Classifications of adverse events are based on the Medical Dictionary for Regulatory Activities (MedDRA v21.1). \n", # nolint
    "Dashed horizontal line represents p-value of 0.05 \n",
    "Dotted horizontal line represents FDR adjusted p-value of approximately 0.05 (when applicable) \n", # nolint
    "Dashed Vertical line represents risk value reference line \n",
    "Totals for the No. of Participants/Events at a higher level are not necessarily the sum of those at the lower levels since a participant may report two or more \n", # nolint
    ifelse(
      tolower(summary_by) == "patients",
      "The number of participants reporting at least 1 occurrence of the event specified.",
      "Event counts are the sum of individual occurrences within that category"
    )
  )


  return(
    list(
      ptly = output,
      plot = p,
      rpt_data = statistics_data,
      title = title,
      footnote = footnote
    )
  )
}
